---
title: "Ingest CCIEA Metadata Database"
author: "Ben Best"
date: "5/12/2021"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 4    
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
shelf(
  dplyr, DT, noaa-iea/ecoidx, googlesheets4, readr)
```

## Read Database

- Source: [ERDDAP_CCIEA_database_2021.20210317 - Google Sheets](https://docs.google.com/spreadsheets/d/1F8H2UFcajLVqq_MIPS0YAUt3ZnSSJP7cZ1hxCsMLW4g/edit?ts=6067b512#gid=747268021)

```{r}
# Google Sheet
# gs_url <- "https://docs.google.com/spreadsheets/d/1F8H2UFcajLVqq_MIPS0YAUt3ZnSSJP7cZ1hxCsMLW4g/edit" # original
gs_url <- "https://docs.google.com/spreadsheets/d/1wknYIkfmyMOZ1-7xNiJbAk9imOX2C3rUcskV_UPrQrs/edit" # editable copy
# shared to shares@iea-uploader.iam.gserviceaccount.com as Editor

gs_json <- "/Volumes/GoogleDrive/My Drive/projects/iea-auto/data/iea-uploader-27c589771060.json"

gs4_auth(path = gs_json)

ecoidx_src <- "~/github/noaa-iea/ecoidx"

datasets <- read_csv(here("data/datasets.csv"), col_types = cols())
datasets
```




