---
title: "Ingest CCIEA Metadata Database"
author: "Ben Best"
date: "5/12/2021"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 4    
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
shelf(
  dplyr, DT, googlesheets4, readr)
```

## Read Database

- Source: [ERDDAP_CCIEA_database_2021.20210317 - Google Sheets](https://docs.google.com/spreadsheets/d/1F8H2UFcajLVqq_MIPS0YAUt3ZnSSJP7cZ1hxCsMLW4g/edit?ts=6067b512#gid=747268021)

```{r}
# Google Sheet
gs_url <- "https://docs.google.com/spreadsheets/d/1F8H2UFcajLVqq_MIPS0YAUt3ZnSSJP7cZ1hxCsMLW4g/edit"

sheet_names(gs_url)
# "Views"              "Documentation"      "Indicator Metadata"
```

### original: Documentation

```{r}
doc <- read_sheet(gs_url, "Documentation", skip = 2)
datatable(doc)
```

### original: Indicator Metadata

```{r}
meta <- read_sheet(gs_url, "Indicator Metadata")
datatable(meta)
```

## Normalize Database

### normalized: providers

```{r}
providers <- meta %>% 
  select(
    pi  = PI, 
    email = Contact) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(providers, "data/providers.csv")
datatable(providers)
```

### normalized: institutions

```{r}
institutions <- meta %>% 
  select(
    institution = Institution) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(institutions, "data/institutions.csv")
datatable(institutions)
```

### normalized: components

```{r}
components <- meta %>% 
  select(
    component    = `Component Section`,
    subcomponent = Subcomponent) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(components, "data/components.csv")
datatable(components)
```

### normalized: datasets

```{r}
datasets <- meta %>% 
  select(
    dataset_id  = `ERDDAP Dataset ID`) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(datasets, "data/datasets.csv")
datatable(datasets)
```

### normalized: timeseries

```{r}
timeseries <- meta %>% 
  select(
    timeseries_id = `CCIEA timeseries ID`,
    dataset_id    = `ERDDAP Dataset ID`,
    institution   = Institution) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(timeseries, "data/timeseries.csv")
datatable(timeseries)
```

### normalized: region

```{r}
regions <- meta %>% 
  select(
    region = region) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(regions, "data/regions.csv")
datatable(regions)
```

### normalized: vars

```{r}
vars <- meta %>% 
  select(
    var_id      = `Variable Name/ERDDAP`,
    var_label   = `Y-axis label (long variable name)`,
    var_units   = `Units`) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(vars, "data/vars.csv")
datatable(vars)
```

### normalized: dataset_vars

```{r}
dataset_vars <- meta %>% 
  select(
    dataset_id    = `ERDDAP Dataset ID`,
    var_id        = `Variable Name/ERDDAP`,
    fld_orig      = `indicator name in PI file`,
    pi            = PI,
    region, latitude, longitude,
    institution   = Institution,
    sampling_freq = `Sampling frequency`,
    sci_name      = `Scientific name`,
    component     = `Component Section`,
    subcomponent  = Subcomponent) %>% 
  mutate(
    across(where(is.list), as.character)) %>% 
  group_by_all() %>% 
  summarize(.groups = "drop")
write_csv(dataset_vars, "data/dataset_vars.csv")
datatable(dataset_vars)
```


